// Auto-generated by generate_position_data.py - do not edit by hand
// Generated: 2026-09-12T18:19:02.632866
var POSITIONS = {
  "schema_version": "1.1",
  "settings": {
    "default_buffer_pct": 0.02,
    "max_accepted_loss": {
      "probing_bet": 0.0025,
      "slug": 0.004
    },
    "max_trade_size_pct": {
      "PB1": 0.025,
      "PB2": 0.025,
      "MM1": 0.04,
      "MM2": 0.03,
      "MM3": 0.02,
      "MM4": 0.01
    },
    "ma_hierarchy": [
      "20D",
      "50D",
      "100D",
      "150D",
      "200D"
    ]
  },
  "investments": [
    {
      "ticker": "AZA-SE",
      "yfinance_ticker": "AZA.ST",
      "name": "Avanza",
      "currency": "SEK",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "AZA-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.01
        },
        {
          "id": "AZA-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.01
        },
        {
          "id": "AZA-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.01
        },
        {
          "id": "AZA-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.02
        },
        {
          "id": "AZA-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.03
        },
        {
          "id": "AZA-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.04
        }
      ]
    },
    {
      "ticker": "BYLOT-GR",
      "yfinance_ticker": "BYLOT.AT",
      "name": "Bally's Intralot",
      "currency": "EUR",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "BYLOT-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.009492
        },
        {
          "id": "BYLOT-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.009492
        },
        {
          "id": "BYLOT-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.009492
        },
        {
          "id": "BYLOT-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.018983
        },
        {
          "id": "BYLOT-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.028475
        },
        {
          "id": "BYLOT-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.037967
        }
      ]
    },
    {
      "ticker": "CARL.B-DK",
      "yfinance_ticker": "CARL-B.CO",
      "name": "Carlsberg",
      "currency": "DKK",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "CARL.B-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.008133
        },
        {
          "id": "CARL.B-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.008133
        },
        {
          "id": "CARL.B-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.008133
        },
        {
          "id": "CARL.B-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.016267
        },
        {
          "id": "CARL.B-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0244
        },
        {
          "id": "CARL.B-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.032533
        }
      ]
    },
    {
      "ticker": "CVSG-GB",
      "yfinance_ticker": "CVSG.L",
      "name": "CVS Group",
      "currency": "GBP",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "CVSG-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.011508
        },
        {
          "id": "CVSG-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.011508
        },
        {
          "id": "CVSG-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.011508
        },
        {
          "id": "CVSG-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.023017
        },
        {
          "id": "CVSG-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.034525
        },
        {
          "id": "CVSG-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.046033
        }
      ]
    },
    {
      "ticker": "ENAV-IT",
      "yfinance_ticker": "ENAV.MI",
      "name": "Enav",
      "currency": "EUR",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "ENAV-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.01015
        },
        {
          "id": "ENAV-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.01015
        },
        {
          "id": "ENAV-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.01015
        },
        {
          "id": "ENAV-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0203
        },
        {
          "id": "ENAV-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.03045
        },
        {
          "id": "ENAV-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0406
        }
      ]
    },
    {
      "ticker": "FEVR-GB",
      "yfinance_ticker": "FEVR.L",
      "name": "Fevertree",
      "currency": "GBP",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "FEVR-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.012075
        },
        {
          "id": "FEVR-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.012075
        },
        {
          "id": "FEVR-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.012075
        },
        {
          "id": "FEVR-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.02415
        },
        {
          "id": "FEVR-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.036225
        },
        {
          "id": "FEVR-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0483
        }
      ]
    },
    {
      "ticker": "HTWS-GB",
      "yfinance_ticker": "HTWS.L",
      "name": "Helios Towers",
      "currency": "GBP",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "HTWS-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.010758
        },
        {
          "id": "HTWS-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.010758
        },
        {
          "id": "HTWS-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.010758
        },
        {
          "id": "HTWS-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.021517
        },
        {
          "id": "HTWS-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.032275
        },
        {
          "id": "HTWS-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.043033
        }
      ]
    },
    {
      "ticker": "RYA-IE",
      "yfinance_ticker": "RYA.IR",
      "name": "Ryanair",
      "currency": "EUR",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "RYA-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.003633
        },
        {
          "id": "RYA-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.003633
        },
        {
          "id": "RYA-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.003633
        },
        {
          "id": "RYA-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.007267
        },
        {
          "id": "RYA-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0109
        },
        {
          "id": "RYA-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.014533
        }
      ]
    },
    {
      "ticker": "THEON-NL",
      "yfinance_ticker": "THEON.AS",
      "name": "Theon",
      "currency": "EUR",
      "choppiness": "standard",
      "notes": "",
      "trades": [
        {
          "id": "THEON-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.00695
        },
        {
          "id": "THEON-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": 0.00695
        },
        {
          "id": "THEON-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.00695
        },
        {
          "id": "THEON-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0139
        },
        {
          "id": "THEON-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.02085
        },
        {
          "id": "THEON-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": 0.0278
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 10",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT10-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT10-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT10-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT10-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT10-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT10-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 11",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT11-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT11-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT11-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT11-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT11-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT11-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 12",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT12-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT12-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT12-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT12-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT12-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT12-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 13",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT13-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT13-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT13-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT13-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT13-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT13-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 14",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT14-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT14-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT14-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT14-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT14-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT14-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 15",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT15-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT15-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT15-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT15-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT15-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT15-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 16",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT16-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT16-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT16-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT16-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT16-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT16-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 17",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT17-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT17-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT17-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT17-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT17-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT17-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 18",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT18-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT18-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT18-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT18-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT18-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT18-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 19",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT19-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT19-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT19-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT19-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT19-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT19-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    },
    {
      "ticker": "",
      "yfinance_ticker": "",
      "name": "Empty slot 20",
      "currency": "",
      "choppiness": "standard",
      "notes": "",
      "is_placeholder": true,
      "trades": [
        {
          "id": "SLOT20-PB1",
          "type": "PB1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT20-PB2",
          "type": "PB2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "50D",
          "initial_stop_ma": "50D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT20-MM1",
          "type": "MM1",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT20-MM2",
          "type": "MM2",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT20-MM3",
          "type": "MM3",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        },
        {
          "id": "SLOT20-MM4",
          "type": "MM4",
          "status": "planned",
          "pivot_price": null,
          "entry_date": null,
          "stop_ma": "100D",
          "initial_stop_ma": "100D",
          "initial_stop_level": null,
          "target_size_pct": null
        }
      ]
    }
  ],
  "stop_breach_alerts": [],
  "last_updated": null
};
